CREATE TABLE [dbo].[AUD_Transaction]
(
	[Id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL PRIMARY KEY,
	[GuidId] [uniqueidentifier] ROWGUIDCOL NOT NULL UNIQUE, 
    [ReportNo] NVARCHAR(500) NOT NULL, 
    [Customer_Id] INT NOT NULL, 
	[Status_Id] INT NOT NULL, 
    [Brand_Id] INT NULL, 
    [Department_Id] INT NULL, 
    [Season_Id] INT NULL, 
    [SeasonYear_Id] INT NULL, 
    [Supplier_Id] INT NOT NULL, 
    [Factory_Id] INT NOT NULL, 
	[AuditType_Id] INT NOT NULL,
    [ServiceDate_From] DATETIME NOT NULL, 
    [ServiceDate_To] DATETIME NOT NULL, 
    [Evalution_Id] INT NULL, 
    [Cus_Booking_Comments] NVARCHAR(1500) NULL, 
    [API_Booking_Comments] NVARCHAR(1500) NULL, 
    [Internal_Comments] NVARCHAR(1500) NULL, 
    [Office_Id] INT NULL, 
    [PO_Number] NVARCHAR(1000) NULL, 
    [CreatedBy] INT NULL, 
    [CreatedOn] DATETIME NULL, 
    [Entity_Id] INT NULL, 
	[ApplicantEmail] NVARCHAR(200),
	[ApplicantName] NVARCHAR(200),
	[ApplicantPhNo] NVARCHAR(200),
    FBMissionId INT,
    FBReportId INT,
    FillingStatus INT,
    FBMissionTitle NVARCHAR(3000),
    FBReportTitle NVARCHAR(3000),
    FBFillingStatus INT, 
    FBReviewStatus INT, 
    FBReportStatus INT,
    ScoreValue nvarchar(100),
    Scorepercentage nvarchar(100),
    Grade nvarchar(100),
    ReportRemarks nvarchar(4000),
    FinalReportPath nvarchar(500),
    PictureReportPath nvarchar(500),
    [CU_ProductCategory] [int] NULL,
    ExternalReportNo nvarchar(100), 
    AuditStartTime nvarchar(50),AuditEndTime nvarchar(50),
    MainCategory nvarchar(100), 
    OtherCategory nvarchar(100),
    Market nvarchar(200),
    FillingValidatedFirstTime nvarchar(100),
    ReviewValidatedFirstTime nvarchar(100),
    LastAuditScore nvarchar(100),
    IsEAQF BIT,
    FOREIGN KEY(Customer_Id) REFERENCES [CU_Customer](Id),
	FOREIGN KEY(Brand_Id) REFERENCES [CU_Brand](Id),
	FOREIGN KEY(Department_Id) REFERENCES [CU_Department](Id),
	FOREIGN KEY(Season_Id) REFERENCES [REF_Season](Id),
	FOREIGN KEY(SeasonYear_Id) REFERENCES [REF_Season_Year](Id),
	FOREIGN KEY(Supplier_Id) REFERENCES [SU_Supplier](Id),
	FOREIGN KEY(Factory_Id) REFERENCES [SU_Supplier](Id),
	FOREIGN KEY(Evalution_Id) REFERENCES [AUD_EvaluationRound](Id),
	FOREIGN KEY(Office_Id) REFERENCES [REF_Location](Id),
	FOREIGN KEY(CreatedBy) REFERENCES [IT_UserMaster](Id),
	FOREIGN KEY([Entity_Id]) REFERENCES [dbo].[AP_Entity](Id),
	FOREIGN KEY([Status_Id]) REFERENCES [dbo].[AUD_Status](Id),
	FOREIGN KEY([AuditType_Id]) REFERENCES [dbo].[AUD_Type](Id),
    CONSTRAINT AUD_Transaction_FBFillingStatus FOREIGN KEY(FBFillingStatus) REFERENCES FB_Status(Id),
    CONSTRAINT AUD_Transaction_FBReviewStatus FOREIGN KEY(FBReviewStatus) REFERENCES FB_Status(Id),
    CONSTRAINT AUD_Transaction_FBReportStatus FOREIGN KEY(FBReportStatus) REFERENCES FB_Status(Id),
    CONSTRAINT AUD_Transaction_FillingStatus FOREIGN KEY (FillingStatus) REFERENCES FB_Status(Id),
    CONSTRAINT [FK_AUD_Transaction_CU_ProductCategory] FOREIGN KEY([CU_ProductCategory]) REFERENCES [dbo].[AUD_CU_ProductCategory] ([Id])
)
