CREATE TABLE [dbo].[AUD_TRAN_FA_Profile]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	[Audit_Id] INT NOT NULL,
	[Created_Date] DATETIME NULL, 
	[No_of_Customer] [nvarchar](1000) NULL,
	[No_Of_Suppliers_Component] [nvarchar](1000) NULL,
	[Annual_production] [nvarchar](1000) NULL,
	[Maximum_Capacity] [nvarchar](1000) NULL,
	[Company_Surface_Area] [nvarchar](1000) NULL,
	[Percentage_Cus_Total_Capacity] [nvarchar](1000) NULL,
	[Possibility_Of_Extension] [nvarchar](1000) NULL,
	[Type_Of_product_Manufactured] [nvarchar](3000) NULL,
	[Types_Of_Brands] [nvarchar](3000) NULL,
	[Number_Of_Sites] [nvarchar](1000) NULL,
	[Company_Open_Time] [nvarchar](1000) NULL,
	[Annual_Holidays] [varchar](1000) NULL,
	[Total_Staff] [int] NULL,
	[Production_Staff] [int] NULL,
	[Administrative_Staff] [int] NULL,
	[Quality_Staff] [int] NULL,
	[Sales_Staff] [int] NULL,
	[Investment_Background] [nvarchar](3000) NULL,
	[Public_Liability_Insurance] [nvarchar](3500) NULL,
	[Industry_TradeAssociation] [nvarchar](3500) NULL,
	[Accrediations] [nvarchar](3500) NULL,
	[Active] [bit] NOT NULL,
	[CreatedOn] DATETIME NOT NULL, 
    [CreatedBy] INT NOT NULL, 
    [DeletedOn] DATETIME NULL, 
    [DeletedBy] INT NULL, 
	FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[IT_UserMaster](Id),
	FOREIGN KEY ([DeletedBy]) REFERENCES [dbo].[IT_UserMaster](Id)	,
    FOREIGN KEY(Audit_Id) REFERENCES [AUD_Transaction](Id)
)
