CREATE TABLE [dbo].[CLM_Transaction]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [ClaimNo] NCHAR(10) NULL, 
    [InspectionNo] INT NULL, 
    [StatusId] INT NULL, 
    [ClaimDate] DATETIME NULL, 
    [RequestedContactName] NVARCHAR(100) NULL, 
    [ReceivedFrom] INT NULL, 
    [ClaimSource] INT NULL, 
    [ClaimDescription] NVARCHAR(MAX) NULL, 
    [CustomerPriority] INT NULL, 
    [CustomerReqRefundAmount] FLOAT NULL, 
    [CustomerReqRefundCurrency] INT NULL, 
    [CustomerComments] NVARCHAR(MAX) NULL, 
    [QCControl_100Goods] BIT NULL, 
    [DefectPercentage] FLOAT NULL, 
    [NoOfPieces] INT NULL, 
    [CompareToAQL] FLOAT NULL, 
    [DefectDistribution] INT NULL, 
    [Color] NVARCHAR(1000) NULL, 
    [DefectCartonInspected] NVARCHAR(500) NULL, 
    [FOB_Price] FLOAT NULL, 
    [FOB_Currency] INT NULL, 
    [Retail_Price] FLOAT NULL, 
    [Retail_Currency] INT NULL, 
    [ClaimValidateResult] INT NULL, 
    [ClaimRemarks] NVARCHAR(2000) NULL, 
    [ClaimRecommendation] NVARCHAR(2000) NULL, 
    [ClaimRefundAmount] FLOAT NULL, 
    [ClaimRefundCurrency] INT NULL, 
    [ClaimRefundRemarks] NVARCHAR(2000) NULL, 
    [RealInspectionFees] FLOAT NULL, 
    [RealInspectionFeesCurrency] INT NULL, 
    [CreatedBy] INT NULL, 
    [CreatedOn] DATETIME NULL, 
    [UpdatedBy] INT NULL, 
    [UpdatedOn] DATETIME NULL, 
    [DeletedBy] INT NULL, 
    [DeletedOn] DATETIME NULL,
    [EntityId] INT NULL,
    [ClaimForm] INT NULL, 
    [AnalyzerFeedback] VARCHAR(MAX) NULL, 
    [AnalyzedOn] DATETIME NULL, 
    [AnalyzedBy] INT NULL, 
    [ValidatedOn] DATETIME NULL, 
    [ValidatedBy] INT NULL, 
    [ClosedOn] DATETIME NULL, 
    [ClosedBy] INT NULL, 
    FOREIGN KEY ([InspectionNo]) REFERENCES Insp_transaction(Id),
    FOREIGN KEY ([StatusId]) REFERENCES CLM_REF_Status(Id),
    FOREIGN KEY ([ReceivedFrom]) REFERENCES CLM_REF_ReceivedFrom(Id),
    FOREIGN KEY ([ClaimSource]) REFERENCES CLM_REF_Source(Id),
    FOREIGN KEY ([CustomerPriority]) REFERENCES CLM_REF_Priority(Id),
    FOREIGN KEY ([CustomerReqRefundCurrency]) REFERENCES REF_Currency(Id),
    FOREIGN KEY ([FOB_Currency]) REFERENCES REF_Currency(Id),
    FOREIGN KEY ([Retail_Currency]) REFERENCES REF_Currency(Id),
    FOREIGN KEY ([ClaimRefundCurrency]) REFERENCES REF_Currency(Id),
    FOREIGN KEY ([RealInspectionFeesCurrency]) REFERENCES REF_Currency(Id),
    FOREIGN KEY ([CreatedBy]) REFERENCES It_UserMaster(Id),
    FOREIGN KEY ([UpdatedBy]) REFERENCES It_UserMaster(Id),
    FOREIGN KEY ([DeletedBy]) REFERENCES It_UserMaster(Id),
	FOREIGN KEY(EntityId) REFERENCES [dbo].[AP_Entity](Id),
    FOREIGN KEY ([AnalyzedBy]) REFERENCES It_UserMaster(Id),
    FOREIGN KEY ([ValidatedBy]) REFERENCES It_UserMaster(Id),
    FOREIGN KEY ([ClosedBy]) REFERENCES It_UserMaster(Id),
)
