CREATE TABLE [dbo].[CU_Customer](
	[Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY ,
	[ZohoCustomerId] bigint,
	[Customer_Name] [nvarchar](500) NOT NULL,
	[EntityId] INT NULL, 
	[Email] NVARCHAR(100) NULL, 
    [Fax] NVARCHAR(100) NULL, 
    [Complexity_Level] INT NULL, 
    [Start_Date] DATETIME NULL, 
    [Website] NVARCHAR(100) NULL, 
    [Others] NVARCHAR(100) NULL, 
    [Prospect_Status] INT NULL, 
    [Skills_Required] INT NULL, 
    [Kam] INT NULL, 
    [Phone] NVARCHAR(100) NULL, 
    [Category] INT NULL, 
    [Marget_Segment] INT NULL, 
    [Business_Country] INT NULL, 
    [Other_Phone] NVARCHAR(100) NULL, 
    [Language] INT NULL, 
    [Business_Type] INT NULL, 
    [Quatation_Name] NVARCHAR(500) NULL, 
    [Ic_Required] BIT NULL, 
    [Gl_Code] NVARCHAR(500) NULL, 
    [Comments] NVARCHAR(MAX) NULL, 
    [Gl_Required] BIT NULL, 
    [Group] INT NULL, 
    [Invoice_Type] INT NULL, 
    [CreatedBy] INT NULL, 
    [CreatedOn] DATETIME NULL, 
    [UpdatedBy] INT NULL, 
    [UpdatedOn] DATETIME NULL, 
    [DeletedBy] INT NULL, 
    [DeletedOn] DATETIME NULL, 
    [Fb_Cus_Id] INT NULL, 
    [BookingDefaultComments] NVARCHAR(MAX) NULL, 
	[Active] BIT,
    [AccountingLeaderId] [int] NULL,
	[ActvitiesLevelId] [int] NULL,
	[RelationshipStatusId] [int] NULL,
	[DirectCompetitor] [nvarchar](2000) NULL,
    [CompanyId] [int] NULL,
    FOREIGN KEY([CompanyId]) REFERENCES [dbo].[AP_Entity](Id),
    FOREIGN KEY([EntityId]) REFERENCES [dbo].[AP_Entity](Id),
	FOREIGN KEY([Group]) REFERENCES [dbo].[CU_CustomerGroup](Id),
	FOREIGN KEY([Prospect_Status]) REFERENCES [dbo].[REF_ProspectStatus](Id),
	FOREIGN KEY([Kam]) REFERENCES [dbo].[HR_Profile](Id),
	FOREIGN KEY([Language]) REFERENCES [dbo].[Language](Id),
	FOREIGN KEY([Marget_Segment]) REFERENCES [dbo].[REF_MarketSegment](Id),
	FOREIGN KEY([Business_Country]) REFERENCES [dbo].[REF_Country](Id),
	FOREIGN KEY([Business_Type]) REFERENCES [dbo].[REF_BusinessType](Id),
	FOREIGN KEY([Invoice_Type]) REFERENCES [dbo].[REF_InvoiceType](Id),
	FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[IT_UserMaster](Id),
	FOREIGN KEY ([UpdatedBy]) REFERENCES [dbo].[IT_UserMaster](Id),
	FOREIGN KEY ([DeletedBy]) REFERENCES [dbo].[IT_UserMaster](Id),
    FOREIGN KEY([AccountingLeaderId]) REFERENCES [dbo].[CU_REF_AccountingLeader] ([Id]),
	FOREIGN KEY([ActvitiesLevelId]) REFERENCES [dbo].[CU_REF_ActivitiesLevel] ([Id]),
	FOREIGN KEY([RelationshipStatusId]) REFERENCES [dbo].[CU_REF_RelationshipStatus] ([Id]),
    [IsEAQF] BIT NULL
	

)
