CREATE TABLE [dbo].[CU_PR_Details] (
[Id] INT NOT NULL PRIMARY KEY identity(1,1),
[CustomerId] int not null,
[BillingMethodId] int not null,
[BillingToId] int not null,
[ServiceId] int not null, 
[CurrencyId] int not null,
[UnitPrice] float not null, 
[ProductPrice] float null,
[TaxIncluded] bit , 
[TravelIncluded] bit, 
[FreeTravelKM] int,
[Remarks] Nvarchar(3000),
[PeriodFrom] datetime,
[PeriodTo] datetime,
[HolidayPrice] FLOAT NULL,
[PriceToEachProduct] BIT NULL,
[MaxProductCount] INT NULL,
[SampleSizeBySet] BIT NULL,
[MinBillingDay] FLOAT NULL,
[MaxSampleSize] INT NULL,
[AdditionalSampleSize] INT NULL,
[AdditionalSamplePrice] FLOAT NULL,
[Quantity8] FLOAT NULL,
[Quantity13] FLOAT NULL,
[Quantity20] FLOAT NULL,
[Quantity32] FLOAT NULL,
[Quantity50] FLOAT NULL,
[Quantity80] FLOAT NULL,
[Quantity125] FLOAT NULL,
[Quantity200] FLOAT NULL,
[Quantity315] FLOAT NULL,
[Quantity500] FLOAT NULL,
[Quantity800] FLOAT NULL,
[Quantity1250] FLOAT NULL,
[InvoiceRequestSelectAll] BIT NULL,
[IsInvoiceConfigured] BIT NULL,
[InvoiceRequestType] INT NULL,
[InvoiceRequestAddress] NVARCHAR(max) NULL,
[InvoiceRequestBilledName] NVARCHAR(2000) NULL,
[PaymentDuration] INT NULL,
[PaymentTerms] NVARCHAR(100) null,
[InvoiceNoDigit] NVARCHAR(100) NULL	,
[BankAccount] INT NULL,
[BillingEntity] INT NULL,
[InvoiceNoPrefix] NVARCHAR(100) NULL,
[InvoiceInspFeeFrom] INT NULL,
[InvoiceTMFeeFrom]  INT NULL,
[InvoiceHotelFeeFrom]  INT NULL,
[InvoiceOtherFeeFrom]  INT NULL,
[InvoiceDiscountFeeFrom] INT NULL,
[InvoiceOffice] INT NULL,
[Active] bit,
[CreatedBy] INT NULL, 
[DeletedBy] INT NULL, 
[UpdatedBy] INT NULL, 
[UpdatedOn] DATETIME, 
[CreatedOn] DATETIME NOT NULL DEFAULT GETDATE(), 
[DeletedOn] DATETIME NULL,
[EntityId] INT NULL,
[BilledQuantityType] INT NULL,
[MaxFeeStyle] Float NULL,
[InvoiceSubject] NVARCHAR(1000) NULL,
[BillingFreequency] INT NULL,
[ManDay_Productivity] Float NULL,
[Manday_ReportCount] int NULL,
[Manday_Buffer] Float NULL,
[SubCategorySelectAll] Bit NULL,
[IsSpecial] Bit NULL,
[InterventionType] INT NULL,
CONSTRAINT CU_PR_Details_EntityId  FOREIGN KEY(EntityId) REFERENCES [dbo].[AP_Entity](Id),
CONSTRAINT FK_CU_PR_Details_CustomerId FOREIGN KEY (CustomerId) REFERENCES [dbo].[Cu_customer](Id),
CONSTRAINT FK_CU_PR_Details_CurrencyId FOREIGN KEY (CurrencyId) REFERENCES [dbo].[ref_currency](Id),
CONSTRAINT FK_CU_PR_Details_BillingMethodId FOREIGN KEY (BillingMethodId) REFERENCES [dbo].[QU_BillMethod](Id),
CONSTRAINT FK_CU_PR_Details_BillingToId FOREIGN KEY (BillingToId) REFERENCES [dbo].[QU_PaidBy](Id),
CONSTRAINT FK_CU_PR_Details_ServiceId FOREIGN KEY (ServiceId) REFERENCES [dbo].[REF_SERVICE](Id),
CONSTRAINT CU_PR_Details_InvoiceRequestType FOREIGN KEY ([InvoiceRequestType]) REFERENCES [dbo].[INV_REF_Request_Type](Id),
CONSTRAINT CU_PR_Details_InvoiceTMFeeFrom FOREIGN KEY ([InvoiceInspFeeFrom]) REFERENCES [dbo].[INV_REF_Fees_From](Id),
CONSTRAINT CU_PR_Details_InvoiceTravleExpenseFrom FOREIGN KEY ([InvoiceTMFeeFrom]) REFERENCES [dbo].[INV_REF_Fees_From](Id),
CONSTRAINT CU_PR_Details_InvoiceHotelFeeFrom FOREIGN KEY ([InvoiceHotelFeeFrom]) REFERENCES [dbo].[INV_REF_Fees_From](Id),
CONSTRAINT CU_PR_Details_InvoiceOtherFeeFrom FOREIGN KEY ([InvoiceOtherFeeFrom]) REFERENCES [dbo].[INV_REF_Fees_From](Id),
CONSTRAINT CU_PR_Details_InvoiceDiscountFeeFrom FOREIGN KEY ([InvoiceDiscountFeeFrom]) REFERENCES [dbo].[INV_REF_Fees_From](Id),
CONSTRAINT CU_PR_Details_InvoiceOffice FOREIGN KEY ([InvoiceOffice]) REFERENCES [dbo].[INV_REF_Office](Id),
CONSTRAINT CU_PR_Details_BillingEntity FOREIGN KEY ([BillingEntity]) REFERENCES [dbo].[REF_Billing_Entity](Id),
CONSTRAINT CU_PR_Details_BankAccount FOREIGN KEY ([BankAccount]) REFERENCES [dbo].[INV_REF_Bank](Id),
CONSTRAINT FK_CU_PR_Details_CreatedBy FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[IT_UserMaster](Id),	
CONSTRAINT FK_CU_PR_Details_DeletedBy FOREIGN KEY ([DeletedBy]) REFERENCES [dbo].[IT_UserMaster](Id),
CONSTRAINT FK_CU_PR_Details_UpdatedBy FOREIGN KEY ([UpdatedBy]) REFERENCES [dbo].[IT_UserMaster](Id),
CONSTRAINT CU_PR_Details_BilledQuantityType FOREIGN KEY ([BilledQuantityType]) REFERENCES [dbo].[INSP_REF_QuantityType](Id),
CONSTRAINT CU_PR_Details_BillingFreequency FOREIGN KEY ([BillingFreequency]) REFERENCES [dbo].[INV_REF_BillingFreequency](Id),
CONSTRAINT CU_PR_Details_InterventionType FOREIGN KEY ([InterventionType]) REFERENCES [dbo].[INV_REF_InterventionType](Id)
)