CREATE TABLE [dbo].[CU_PR_TRAN_Subcategory]
(
	  [Id] INT IDENTITY(1,1) PRIMARY KEY,	  
	  [Cu_Price_Id] [int],	
	  [Sub_Category2Id] [int],	
	  [MandayProductivity] [int],	
	  [MandayReports] [int],	
	  [MandayBuffer] [float],	
	  [UnitPrice] [float],	
	  [AQL_QTY_8] [float],		   
	  [AQL_QTY_13] [float],	   
	  [AQL_QTY_20] [float],	   
	  [AQL_QTY_32] [float],
	  [AQL_QTY_50] [float],
	  [AQL_QTY_80] [float],
	  [AQL_QTY_125] [float],
	  [AQL_QTY_200] [float],	
	  [AQL_QTY_315] [float],	
	  [AQL_QTY_500] [float],	
	  [AQL_QTY_800] [float],	
	  [AQL_QTY_1250] [float],
	  [Active] BIT,
	  [CreatedBy] INT NULL, 
      [CreatedOn] DATETIME NULL,     
	  [DeletedBy] [INT] NULL, 
      [DeletedOn] [DATETIME] NULL,
	  CONSTRAINT CU_PR_TRAN_Subcategory_Cu_Price_Id FOREIGN KEY ([Cu_Price_Id]) REFERENCES [dbo].[CU_PR_Details](Id),
	  CONSTRAINT CU_PR_TRAN_Subcategory_Sub_Category2Id FOREIGN KEY ([Sub_Category2Id]) REFERENCES [dbo].[REF_ProductCategory_Sub2](Id),
	  CONSTRAINT CU_PR_TRAN_Subcategory_CreatedBy	FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[IT_UserMaster](Id),
	  CONSTRAINT CU_PR_TRAN_Subcategory_DeletedBy	FOREIGN KEY ([DeletedBy]) REFERENCES [dbo].[IT_UserMaster](Id)
)
