CREATE TABLE [dbo].[EC_ExpencesClaims](
	[Id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL PRIMARY KEY,
	[StaffId] [int] NOT NULL,
	[CountryId] [int] NOT NULL,
	[PaymentTypeId] [int] NOT NULL,
	[LocationId] [int] NOT NULL,
	[StatusId] [int] NOT NULL,
	[ApprovedId] [int] NULL,
	[ApprovedDate] [datetime] NULL,
	[CheckedId] [int] NULL,
	[CheckedDate] [datetime] NULL,
	[PaidId] [int] NULL,
	[PaidDate] [datetime] NULL,
	[RejectId] [int] NULL,
	[RejectDate] [datetime] NULL,
	[CancelId] [int] NULL,
	[CancelDate] [datetime] NULL,
	[ClaimNo] [nvarchar](100) NOT NULL,
	[IsINsp]  [bit] NOT NULL,
	[ClaimDate] [datetime] NOT NULL,
	[active] [bit] NOT NULL DEFAULT(1),	
	[CreatedDate] [datetime] NOT NULL,
	[ExpensePurpose] [nvarchar](4000) NULL,
	[EntityId] INT NOT NULL,
	[Comment] NVARCHAR(600) NULL,
	[ClaimTypeId] INT NULL,
	FOREIGN KEY([EntityId]) REFERENCES [AP_Entity](Id),
	FOREIGN KEY([StaffId]) REFERENCES [dbo].[HR_Staff](Id),
	FOREIGN KEY([CountryId]) REFERENCES [dbo].[REF_Country](Id),
	FOREIGN KEY([PaymentTypeId]) REFERENCES  [dbo].[EC_PaymenTypes](Id),
	FOREIGN KEY([LocationId]) REFERENCES  [dbo].[REF_Location](Id),
	FOREIGN KEY([StatusId]) REFERENCES  [dbo].[EC_ExpClaimStatus](Id),
	FOREIGN KEY([ApprovedId]) REFERENCES  [dbo].[IT_UserMaster](Id),
	FOREIGN KEY([CheckedId]) REFERENCES  [dbo].[IT_UserMaster](Id),
	FOREIGN KEY([PaidId]) REFERENCES  [dbo].[IT_UserMaster](Id),
	FOREIGN KEY([CancelId]) REFERENCES  [dbo].[IT_UserMaster](Id),
	FOREIGN KEY([RejectId]) REFERENCES  [dbo].[IT_UserMaster](Id),
	FOREIGN KEY([ClaimTypeId]) REFERENCES  [dbo].[EC_ExpenseClaimtype](Id)
	)
