CREATE TABLE [dbo].[ENT_Pages_Fields]
(
	[Id INT IDENTITY(1,1) PRIMARY KEY,
	[FieldName] NVARCHAR(50),
	[ENTPageId] INT,
	[EntityId] INT,
	[CustomerId] INT,
	[Active] BIT,
	CONSTRAINT FK_ENT_PAGE_FIELD_PAGEID FOREIGN KEY([ENTPageId]) REFERENCES [dbo].[ENT_Pages],
	CONSTRAINT FK_ENT_PAGE_FIELD_ENTITY_ID FOREIGN KEY([EntityId]) REFERENCES [dbo].[AP_ENTITY],
	CONSTRAINT FK_ENT_PAGE_FIELD_CUSTOMER_ID FOREIGN KEY([CustomerId]) REFERENCES [dbo].[CU_CUSTOMER]
)