CREATE TABLE [dbo].[ES_Details]
(
  [Id] INT NOT NULL PRIMARY KEY identity(1,1),  
  [CustomerId] int NOT NULL,
  [ServiceId] int NOT NULL,
  [TypeId] int NOT NULL,
  [Is_Include_CC] BIT,
  [Is_Include_SC] BIT,
  [Is_Include_FC] BIT, 
  [Is_Include_MC] BIT, 
  [Active] BIT,
  [CreatedOn] DATETIME NOT NULL default getdate(),  
  [CreatedBy] int NULL, 
  [Report_Send_Type] int null,
  [Email_Subject] int null,
  [Email_Size] int null,
  [Report_In_Email] int null,
  [Recipient_Name] nvarchar(max),
  [No_Of_Reports] int Null,
  [File_Name_Id] INT NULL,
  [IsPictureFileInEmail] BIT NULL,
  [UpdatedBy] int null,
  [UpdatedOn] datetime null,
  [DeletedBy] int null,
  [DeletedOn] datetime null,
  CONSTRAINT ES_Details_CustomerId FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[CU_Customer](Id),
  CONSTRAINT ES_Details_ServiceId FOREIGN KEY ([ServiceId]) REFERENCES [dbo].[REF_Service](Id),
  CONSTRAINT ES_Details_TypeId FOREIGN KEY ([TypeId]) REFERENCES [dbo].[ES_Type](Id),
  CONSTRAINT ES_Details_CreatedBy FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[IT_UserMaster](Id),
  CONSTRAINT FK_ES_Details_Report_In_Email FOREIGN KEY (Report_In_Email) REFERENCES  [dbo].[ES_REF_Report_In_Email](Id),
  CONSTRAINT FK_ES_Details_Email_Size FOREIGN KEY (Email_Size) REFERENCES  [dbo].[ES_REF_Email_Size](Id),
  CONSTRAINT FK_ES_Details_Email_Subject FOREIGN KEY (Email_Subject) REFERENCES  [dbo].[ES_SU_Template_Master](Id),
  CONSTRAINT FK_ES_Details_Report_Send_Type FOREIGN KEY (Report_Send_Type) REFERENCES  [dbo].[ES_REF_Report_Send_Type](Id),
  CONSTRAINT FK_ES_Details_File_Name_Id FOREIGN KEY([File_Name_Id]) REFERENCES [dbo].[ES_SU_Template_Master](Id),
  CONSTRAINT FK_ES_Details_UpdatedBy FOREIGN KEY ([UpdatedBy]) REFERENCES IT_UserMaster (Id),
  CONSTRAINT FK_ES_Details_DeletedBy FOREIGN KEY ([DeletedBy]) REFERENCES IT_UserMaster (Id)
)
