CREATE TABLE FB_Report_FabricDefects(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	FbreportdetailsId INT NULL,
	InspPoTransactionId INT NULL,
	InspColorTransactionId INT NULL,
	LengthUnit nvarchar(100) NULL,
	DyeLot nvarchar(200) NULL,
	RollNumber nvarchar(100) NULL,
	Result nvarchar(100) NULL,
	AcceptanceCriteria nvarchar(200) NULL,
	Points100Sqy nvarchar(200) NULL,
	LengthOriginal nvarchar(200) NULL,
	LengthActual nvarchar(200) NULL,
	WeightOriginal nvarchar(200) NULL,
	WeightActual nvarchar(200) NULL,
	WidthOriginal nvarchar(200) NULL,
	WidthActual nvarchar(200) NULL,
	Code nvarchar(100) NULL,
	Description nvarchar(200) NULL,
	Location nvarchar(200) NULL,
	Point nvarchar(200) NULL,
	Active BIT,
	CreatedOn DATETIME,
	DeletedOn DATETIME,
	CONSTRAINT FB_Report_FabricDefects_FbreportdetailsId FOREIGN KEY(FbreportdetailsId) REFERENCES FB_Report_Details(Id),
	CONSTRAINT FB_Report_FabricDefects_InspPoTransactionId FOREIGN KEY(InspPoTransactionId) REFERENCES INSP_PurchaseOrder_Transaction(Id),
	CONSTRAINT FB_Report_FabricDefects_InspColorTransactionId FOREIGN KEY(InspColorTransactionId) REFERENCES INSP_PurchaseOrder_Color_Transaction(Id)
)