CREATE TABLE [dbo].[FB_Report_Quantity_Details]
(
	[Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[FbReportDetailId] int NOT NULL,
	[InspPoTransactionId] int NOT NULL,
	[OrderQuantity] int NULL,
	[PresentedQuantity] int NULL,
    [InspectedQuantity] int NULL,
	[ShipmentQuantity] int NULL,
	[CreatedOn] DATETIME NULL,
	[DeletedOn] DATETIME NULL, 
	[Active] BIT NULL,
	[ProductionStatus] FLOAT NULL,
	[PackingStatus] FLOAT NULL,
	[TotalUnits] FLOAT NULL,
	[TotalCartons] FLOAT NULL,
	[FinishedPackedUnits] FLOAT NULL,
	[FinishedUnpackedUnits] FLOAT NULL,
	[NotFinishedUnits] FLOAT NULL,
	[SelectCtnQty] FLOAT NULL,
	[SelectCtnNO] NVARCHAR(max) NULL,
	Fabric_Points100Sqy FLOAT NULL,
	Fabric_AcceptanceCriteria FLOAT NULL,
	ProducedQuantity FLOAT NULL,
	Fabric_OverLessProducedQty nvarchar(100) NULL,
	Fabric_RejectedQuantity FLOAT NULL,
	Fabric_RejectedRolls FLOAT NULL,
	Fabric_DemeritPts FLOAT NULL,
	Fabric_Tolerance FLOAT NULL,
	Fabric_Rating nvarchar(100) NULL,
	FOREIGN KEY(FbReportDetailId) REFERENCES [FB_Report_Details](Id),
	FOREIGN KEY(InspPoTransactionId) REFERENCES [INSP_PurchaseOrder_Transaction](Id)	
)
