CREATE TABLE [dbo].[FB_Report_Details]
(
	[Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[MissionTitle] NVARCHAR(1500) NULL, 
    [ReportTitle] NVARCHAR(1500) NULL, 
	[MainProductPhoto] NVARCHAR(1000) NULL, 
	[FinalReportPath] NVARCHAR(1000) NULL, 
    [ServiceFromDate] DATETIME  NULL, 
    [ServiceToDate] DATETIME  NULL, 
    [Fb_Filling_Status] INT NULL, 
	[Fb_Review_Status] INT NULL, 
	[Fb_Report_Status] INT NULL, 
	[OverAllResult] NVARCHAR(1500) NULL, 
	[ReportSummaryLink] NVARCHAR(4000) NULL,
	[InspectionStartTime] DATETIME NULL,
	[InspectionEndTime] DATETIME NULL,
	[ProductionStatus] FLOAT NULL,
	[PackingStatus] FLOAT NULL,
	[CriticalMax] INT,
	[MajorMax] INT,
	[MinorMax] INT,
	[ResultId] INT  NULL, 
	[CreatedOn] DATETIME NULL,
	[DeletedOn] DATETIME NULL, 
    [Active] BIT NULL,
	[FB_Report_Map_Id] INT NULL,
	[Inspection_Id] INT NULL,
	FinalManualReportPath NVARCHAR(1000),
	[Aql_Level] INT NULL,
	[SampleSize] INT NULL,
	[Found_Critical] INT NULL,
	[Found_Major] INT NULL,
	[Found_Minor] INT NULL,
	[Aql_Critical] FLOAT NULL,
	[Aql_Major] FLOAT NULL,
	[Aql_Minor] FLOAT NULL,
	[OrderQty] INT NULL,
	[InspectedQty] INT NULL,
	[PresentedQty] INT NULL,
	[Report_Picture_Path] NVARCHAR(1000) NULL,
	Fabric_NoOfRollsPresented FLOAT NULL,
	Fabric_NoOfLotsPresented FLOAT NULL,
	Fabric_ProducedQtyRoll FLOAT NULL,
	Fabric_PresentedQtyRoll FLOAT NULL,
	Fabric_InspectedQtyRoll FLOAT NULL,
	Fabric_AcceptedQtyRoll FLOAT NULL,
	Fabric_RejectedQtyRoll FLOAT NULL,
	Fabric_MachineSpeed Nvarchar(200) NULL,
	Fabric_Type nvarchar(200) NULL,
	Fabric_TypeCheck  nvarchar(200) NULL,
	Fabric_factoryType nvarchar(200) NULL,
	FillingValidatedFirstTime nvarchar (100), 
	ReviewValidatedFirstTime nvarchar (100), 
	DACorrelationDone nvarchar (100),
	FactoryTourDone nvarchar (100),
	FactoryTourResult  nvarchar (100),
	ExternalReportNumber nvarchar(200),
	ReportType nvarchar(200), 
	Origin nvarchar(100), 
	ShipMode nvarchar(100), 
	Othercategory nvarchar(200),
	Market  nvarchar(200),
	TotalScore nvarchar(100),
	Grade nvarchar(100), 
	LastAuditScore nvarchar(100),
	FOREIGN KEY ([Fb_Filling_Status]) REFERENCES [dbo].[FB_Status](Id),
	FOREIGN KEY ([Fb_Review_Status]) REFERENCES [dbo].[FB_Status](Id),
	FOREIGN KEY ([Fb_Report_Status]) REFERENCES [dbo].[FB_Status](Id),
	FOREIGN KEY ([ResultId]) REFERENCES [dbo].[FB_Report_Result](Id),
	CONSTRAINT FB_Report_Details_Inspection_Id FOREIGN KEY ([Inspection_Id]) REFERENCES [dbo].[INSP_Transaction](Id),
	CONSTRAINT FK_FB_Report_Details_Aql_Level FOREIGN KEY(Aql_Level) REFERENCES [REF_LevelPick1](Id)
)
