
CREATE TABLE [dbo].[HR_Leave](
	[Id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL PRIMARY KEY,
	[StaffId] [int] NOT NULL,
	[LeaveType_Id] [int] NOT NULL,
	[Date_Begin] [datetime] NOT NULL,
	[Date_End] [datetime] NOT NULL,
	[Number_Of_Days] [float] NOT NULL,
	[Comments] [nvarchar](200) NULL,
	[Checked_Id] [int] NULL,
	[Comments1] [nvarchar](100) NULL,
	[Approved_Id] [int] NULL,
	[Comments2] [nvarchar](100) NULL,
	[Status] [int] NULL,
	[Approved_Leave_days] [float] NULL,
	[Leave_application_date] [datetime] NULL,
	IdTypeStartDate INT NOT NULL,
	IdTypeEndDate INT NOT NULL,	
	ApprovedOn DATETIME,
	CancelledOn DATETIME,
	RejectedOn DATETIME,
	FOREIGN KEY([IdTypeStartDate]) REFERENCES [dbo].[HR_HolidayDayType](Id),
	FOREIGN KEY([IdTypeEndDate]) REFERENCES [dbo].[HR_HolidayDayType](Id),
	FOREIGN KEY([StaffId]) REFERENCES [dbo].[HR_Staff](Id),
	FOREIGN KEY([Status]) REFERENCES [dbo].[HR_Leave_Status](Id),
	FOREIGN KEY([LeaveType_Id]) REFERENCES [dbo].[HR_Leave_Type](Id),
	FOREIGN KEY([Checked_Id]) REFERENCES [dbo].[IT_UserMaster](Id),
	FOREIGN KEY([Approved_Id]) REFERENCES [dbo].[IT_UserMaster](Id))