CREATE TABLE [dbo].[INSP_Product_Transaction]
(
	[Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,	
    [Inspection_Id] INT NOT NULL, 
	[Product_Id] INT NOT NULL, 
    [AQL] INT NULL, 
    [Critical] INT NULL, 
    [Major] INT NULL, 
    [Minor] INT NULL, 
	[Unit] INT NOT NULL, 
	[UnitCount] INT  NULL, 
	[TotalBookingQuantity] INT NOT NULL, 			
	[Combine_Product_Id] INT  NULL,
	[AQL_Quantity] INT NULL,
    [Combine_AQL_Quantity] INT NULL,
    [CreatedBy] INT NULL, 
    [CreatedOn] DATETIME NULL, 
	[UpdatedBy] INT NULL, 
    [UpdatedOn] DATETIME NULL, 
    [DeletedBy] INT NULL, 
    [DeletedOn] DATETIME NULL, 
	[Remarks] nvarchar(max) null,
	[SampleType] INT NULL,
    [Active] BIT NULL,
	[Fb_Report_Id] INT NULL, 
    [IsEcopack] BIT NULL, 
    [IsDisplayMaster] BIT NULL, 
    [FBTemplateId] INT NULL, 
	[Parent_Product_Id] INT NULL,
	[EntityId] INT NULL,
	[AsReceivedDate] DATETIME NULL,
	[TfReceivedDate] DATETIME NULL,
	[ProductionStatus] INT NULL,
	[PackingStatus] INT NULL,
	[IsGoldenSampleAvailable]  BIT null,
	[GoldenSampleComments] NVARCHAR(500) null,
	[IsSampleCollectionBit] BIT null,
	[SampleCollectionComments] NVARCHAR(500) null,
    FOREIGN KEY([Inspection_Id]) REFERENCES [dbo].[INSP_Transaction](Id),
	FOREIGN KEY([AQL]) REFERENCES [dbo].[REF_LevelPick1](Id),
	FOREIGN KEY([Critical]) REFERENCES [dbo].[REF_Pick1](Id),
	FOREIGN KEY([Major]) REFERENCES [dbo].[REF_Pick1](Id),
	FOREIGN KEY([Minor]) REFERENCES [dbo].[REF_Pick1](Id),
	FOREIGN KEY([Unit]) REFERENCES [dbo].[REF_Unit](Id),
	FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[IT_UserMaster](Id),
	FOREIGN KEY ([UpdatedBy]) REFERENCES [dbo].[IT_UserMaster](Id),
	FOREIGN KEY ([DeletedBy]) REFERENCES [dbo].[IT_UserMaster](Id),
	FOREIGN KEY ([Fb_Report_Id]) REFERENCES [FB_Report_Details](Id),
	FOREIGN KEY ([Product_Id]) REFERENCES [CU_Products](Id),
	FOREIGN KEY([FBTemplateId]) REFERENCES [FB_Report_Template](id),
	FOREIGN KEY ([SampleType]) REFERENCES REF_SampleType(Id),
	CONSTRAINT FK_INSP_Prd_Trans_ParentProduct FOREIGN KEY ([Parent_Product_Id]) REFERENCES [dbo].[CU_Products](Id),
	CONSTRAINT FK_INSP_Product_Transaction_EntityId FOREIGN KEY(EntityId) REFERENCES [dbo].[AP_Entity](Id),
	CONSTRAINT FK__INSP_Prod__Production__Status FOREIGN KEY (ProductionStatus) REFERENCES [dbo].[INSP_REF_ProductionStatus](Id),
	CONSTRAINT FK__INSP_Prod__Packing__Status FOREIGN KEY (PackingStatus) REFERENCES [dbo].[INSP_REF_PackingStatus](Id)
)
