CREATE TABLE [dbo].[INSP_Transaction]
(
	[Id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL PRIMARY KEY, 
	[GuidId] [uniqueidentifier] ROWGUIDCOL NOT NULL UNIQUE, 
    [InternalReferencePO] NVARCHAR(1500) NULL, 
    [Customer_Id] INT NOT NULL, 
    [Supplier_Id] INT NOT NULL, 
    [Factory_Id] INT NULL, 
    [Status_Id] INT NOT NULL,  
    [Season_Id] INT NULL, 
    [SeasonYear_Id] INT NULL, 
    [ServiceDate_From] DATETIME NOT NULL, 
    [ServiceDate_To] DATETIME NOT NULL, 
    [Cus_Booking_Comments] NVARCHAR(MAX) NULL, 
    [API_Booking_Comments] NVARCHAR(MAX) NULL, 
    [Internal_Comments] NVARCHAR(MAX) NULL, 
    [Office_Id] INT NULL, 	
    [CreatedBy] INT NULL, 
    [CreatedOn] DATETIME NULL, 
	[UpdatedBy] INT NULL, 
    [UpdatedOn] DATETIME NULL, 
    [Entity_Id] INT NOT NULL, 
	[CollectionId] INT NULL,
	[PriceCategoryId] INT NULL,
    [Applicant_Name] NVARCHAR(200) NULL, 
    [Applicant_Email] NVARCHAR(200) NULL,	
    [Applicant_PhoneNo] NVARCHAR(200) NULL, 
	[Flexible_Inspection_Date] BIT NULL,
    [PreviousBookingNo] INT NULL, 
    [ReInspectionType] INT NULL, 
    [IsPickingRequired] BIT NULL DEFAULT 0, 
	[CustomerBookingNo] NVARCHAR(500) NULL,
    [SplitPreviousBookingNo] INT NULL, 
	[Schedule_Comments] NVARCHAR(MAX) NULL,
    [Fb_Mission_Id] INT NULL,
	[Fb_Mission_Status] INT NULL,
    [QCBookingComments] NVARCHAR(max) NULL, 
	[FirstServiceDate_From] DATETIME  NULL, 
    [FirstServiceDate_To] DATETIME  NULL, 
	[IsProcessing] BIT NULL DEFAULT 0, 
	[CompassBookingNo] NVARCHAR(1500) NULL,
	IsCombineRequired BIT NULL,
	BusinessLine INT,
	CuProductCategory INT,
	Season INT,
	InspectionLocation INT,
	ShipmentPort NVARCHAR(500),
	ShipmentDate DATETIME,
	EAN NVARCHAR(500),
	CONSTRAINT FK_INSP_INSPECTION_LOCATION FOREIGN KEY(InspectionLocation) REFERENCES [dbo].[INSP_REF_InspectionLocation],
	CONSTRAINT FK_INSP_SEASON FOREIGN KEY(Season) REFERENCES [dbo].[REF_Season],
	CONSTRAINT FK_INSP_CU_PRODUCT_CATEGORY FOREIGN KEY(CuProductCategory) REFERENCES [dbo].[CU_ProductCategory],
	CONSTRAINT FK_INSP_Business_Line FOREIGN KEY(BusinessLine) REFERENCES [dbo].[REF_BUSINESS_LINE],
    FOREIGN KEY(Customer_Id) REFERENCES [CU_Customer](Id),	
	FOREIGN KEY(Season_Id) REFERENCES [REF_Season](Id),
	FOREIGN KEY(SeasonYear_Id) REFERENCES [REF_Season_Year](Id),
	FOREIGN KEY(Supplier_Id) REFERENCES [SU_Supplier](Id),
	FOREIGN KEY(Factory_Id) REFERENCES [SU_Supplier](Id),
	FOREIGN KEY(Office_Id) REFERENCES [REF_Location](Id),
	FOREIGN KEY(CreatedBy) REFERENCES [IT_UserMaster](Id),
	FOREIGN KEY([Entity_Id]) REFERENCES [dbo].[AP_Entity](Id),
	FOREIGN KEY([Status_Id]) REFERENCES [dbo].[INSP_Status](Id),
	FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[IT_UserMaster](Id),
	FOREIGN KEY ([UpdatedBy]) REFERENCES [dbo].[IT_UserMaster](Id),
	FOREIGN KEY ([Fb_Mission_Status]) REFERENCES [dbo].[FB_Status](Id),
	FOREIGN KEY ([CollectionId]) REFERENCES [CU_Collection](Id),
	FOREIGN KEY([PriceCategoryId]) REFERENCES [CU_PriceCategory](Id),
	CONSTRAINT FK_INSP_TRANSACTION_RE_INSPECTION_TYPE FOREIGN KEY([ReInspectionType]) REFERENCES [REF_ReInspectionType](Id),
	[ReportRequest] INT NULL,
	[IsSameDayReport]  BIT NULL,
	[IsInspectionCertificate]  BIT NULL,
	[IsEAQF] BIT NULL,
	CONSTRAINT FK__INSP_Tran__Report_Request FOREIGN KEY (ReportRequest) REFERENCES [dbo].[INSP_REF_ReportRequest](Id)
)
