CREATE TABLE [dbo].[INSP_TRAN_Hold_reason]
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	ReasonType INT,
	Comment NVARCHAR(MAX),
	Inspection_Id INT,
	Active BIT,
	CreatedOn DATETIME,
	CreatedBy INT,
	CONSTRAINT FK_HOLD_REASON FOREIGN KEY (ReasonType) REFERENCES [INSP_REF_Hold_Reasons],
	CONSTRAINT FK_INSPECTION_ID FOREIGN KEY (Inspection_Id) REFERENCES [INSP_TRANSACTION]
)