CREATE TABLE [INV_MAN_Transaction]
(
	[Id] INT IDENTITY(1,1)  PRIMARY KEY,
	[InvoiceNo] NVARCHAR(100),
	[BilledName] NVARCHAR(500),
	[CustomerId] INT NOT NULL,
	[InvoiceToId] INT NOT NULL,
	[InvoiceDate] DATE NULL,
	[BilledAddress] NVARCHAR(2000),
	[Attn] NVARCHAR(1000), 
	[Email] NVARCHAR(2000),
	[Currency] INT,
	[ServiceId] INT NULL,
	[SupplierId] INT NULL,
	[CountryId] INT NULL,
	[ServiceType] INT NULL,
	[OfficeId] INT NOT NULL, 
	[PaymentTerms] NVARCHAR(1000),
	[PaymentDuration] INT, 
	[BankId] INT NOT NULL, 
	[FromDate] DATE,
	[ToDate] DATE, 
	[TotalAmount] FLOAT, 
	[Tax] FLOAT,
	[TaxAmount] FLOAT, 
	[Status] INT NOT NULL,
	[CreatedBy] INT, 
	[CreatedOn] DATETIME, 
	[DeletedBy] INT, 
	[DeletedOn] DATETIME,
	[UpdatedBy] INT,
	[UpdatedOn] DATETIME,	
	[BookingNo] int,
	[PaymentMode] int,
	[PaymentRef] nvarchar(200),
	[AuditId] int null,
	CONSTRAINT INV_MAN_Transaction_CustomerId FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Cu_Customer](Id),
	CONSTRAINT INV_MAN_Transaction_SupplierId FOREIGN KEY ([SupplierId]) REFERENCES [dbo].[Su_Supplier](Id),
	CONSTRAINT INV_MAN_Transaction_InvoiceToId FOREIGN KEY ([InvoiceToId]) REFERENCES [dbo].[QU_PaidBy](Id),
	CONSTRAINT INV_MAN_Transaction_Currency FOREIGN KEY ([Currency]) REFERENCES [dbo].[REF_Currency](Id),
	CONSTRAINT INV_MAN_Transaction_ServiceId FOREIGN KEY ([ServiceId]) REFERENCES [dbo].[REF_Service](Id),
	CONSTRAINT INV_MAN_Transaction_ServiceType FOREIGN KEY ([ServiceType]) REFERENCES [dbo].[REF_ServiceType],
	CONSTRAINT INV_MAN_Transaction_OfficeId FOREIGN KEY ([OfficeId]) REFERENCES [dbo].[INV_REF_Office](Id),
	CONSTRAINT INV_MAN_Transaction_BankId FOREIGN KEY ([BankId]) REFERENCES [dbo].[INV_REF_Bank](Id),
	CONSTRAINT INV_MAN_Transaction_Status FOREIGN KEY ([Status]) REFERENCES [dbo].[INV_Status](Id),
	CONSTRAINT INV_MAN_Transaction_CreatedBy FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[It_UserMaster](Id),
	CONSTRAINT INV_MAN_Transaction_Deletedby FOREIGN KEY ([DeletedBy]) REFERENCES [dbo].[It_UserMaster](Id),
	CONSTRAINT INV_MAN_Transaction_UpdatedBy FOREIGN KEY ([UpdatedBy]) REFERENCES [dbo].[It_UserMaster](Id),
	CONSTRAINT FK_INV_MAN_Transaction_BookingNo foreign key(BookingNo) references INSP_Transaction(Id),
	CONSTRAINT FK_INV_MAN_Transaction_AuditId FOREIGN KEY(AuditId) REFERENCES AUD_Transaction(Id),
	CONSTRAINT FK_INV_MAN_Transaction_PaymentMode FOREIGN KEY (PaymentMode) REFERENCES [dbo].[INV_REF_PaymentMode](Id)
)

