CREATE TABLE [dbo].[INV_EXF_Transaction]
(
	[Id] INT NOT NULL PRIMARY KEY identity(1,1)
	,InspectionId int null,
     AuditId int null,
	CustomerId int,
	StatusId int null,  SupplierId  int null,  FactoryId int null, BilledTo int,
	CurrencyId int, ServiceId int, Tax float, BankId int, [PaymentDate] datetime, Remarks nvarchar(max),
	BillingEntityId int, InvoiceId int, ExtraFeeInvoiceNo nvarchar(max), [PaymentStatus] int,
	CreatedOn datetime not null default getdate(),  CreatedBy int null, UpdatedBy int null, 
	UpdatedOn datetime  null, DeletedBy int null, DeletedOn datetime  null,  Active bit,
	ExtraFeeSubTotal float, TaxAmount float, TotalExtraFee float,
	ExtraFeeInvoiceDate datetime,
	[OfficeId] INT NULL, 
	[BilledName] NVARCHAR(500) NULL, 
    [BilledAddress] NVARCHAR(1000) NULL, 
    [PaymentTerms] NVARCHAR(500) NULL, 
    [PaymentDuration] INT NULL, 
    CONSTRAINT INV_EXF_Transaction_InspectionId FOREIGN KEY (InspectionId) REFERENCES [dbo].[INSP_Transaction](Id),
    CONSTRAINT INV_EXF_Transaction_AuditId FOREIGN KEY (AuditId) REFERENCES [dbo].[AUD_Transaction](Id),
	CONSTRAINT INV_EXF_Transaction_CustomerId FOREIGN KEY (CustomerId) REFERENCES [dbo].[CU_Customer](Id),
	CONSTRAINT INV_EXF_Transaction_StatusId FOREIGN KEY (StatusId) REFERENCES [dbo].[INV_EXF_Status](Id),
	CONSTRAINT INV_EXF_Transaction_FactoryId FOREIGN KEY (FactoryId) REFERENCES [dbo].[SU_Supplier](Id),
	CONSTRAINT INV_EXF_Transaction_BilledTo FOREIGN KEY (BilledTo) REFERENCES [dbo].[QU_PaidBy](Id),
	CONSTRAINT INV_EXF_Transaction_CurrencyId FOREIGN KEY (CurrencyId) REFERENCES [dbo].[REF_CURRENCY](Id),
	CONSTRAINT INV_EXF_Transaction_ServiceId FOREIGN KEY (ServiceId) REFERENCES [dbo].[REF_SERVICE](Id),
	CONSTRAINT INV_EXF_Transaction_InvoiceId FOREIGN KEY (InvoiceId) REFERENCES [dbo].[INV_AUT_TRAN_Details](Id),
	CONSTRAINT INV_EXF_Transaction_BillingEntityId FOREIGN KEY (BillingEntityId) REFERENCES [dbo].[REF_Billing_Entity](Id),
	CONSTRAINT INV_EXF_Transaction_BankId FOREIGN KEY (BankId) REFERENCES [dbo].[INV_REF_Bank](Id),
	CONSTRAINT INV_EXF_Transaction_SupplierId FOREIGN KEY (SupplierId) REFERENCES [dbo].[SU_Supplier](Id),
	CONSTRAINT INV_EXF_Transaction_PaymentStatus FOREIGN KEY ([PaymentStatus]) REFERENCES [dbo].[INV_Payment_Status](Id),
	CONSTRAINT INV_EXF_Transaction_CreatedBy FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[IT_UserMaster](Id),
	CONSTRAINT INV_EXF_Transaction_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES [dbo].[IT_UserMaster](Id),
	CONSTRAINT INV_EXF_Transaction_DeletedBy FOREIGN KEY (DeletedBy) REFERENCES [dbo].[IT_UserMaster](Id),
	CONSTRAINT INV_EXF_Transaction_OfficeId FOREIGN KEY (OfficeId) REFERENCES [dbo].[INV_REF_Office](Id)
)
