create table INV_TM_Details
(
Id int not null primary key identity(1,1),
CustomerId int null,
TravelMatrixTypeId int not null,
CountryId int not null,
ProvinceId int not null,
CityId int null,
CountyId int null,
InspPortCountyId int  null,
[InspPortCityId] INT NULL,
DistanceKM float null,
TravelTime float null,
BusCost float null,
TrainCost float null,
TaxiCost float null,
HotelCost float null,
OtherCost float null,
MarkUpCost float null,
AirCost float null,
MarkUpAirCost float null,
TravelCurrencyId int null,
SourceCurrencyId int null,
FixedExchangeRate float null,
Remarks nvarchar(2000) null,
Active bit, 
CreatedOn datetime default getdate(),
UpdatedOn datetime,
DeletedOn datetime,
UpdatedBy int null,
DeletedBy int null,
CreatedBy int null,
CONSTRAINT INV_TM_Details_CustomerId  FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Cu_Customer](Id),	
CONSTRAINT INV_TM_Details_TravelMatrixTypeId FOREIGN KEY ([TravelMatrixTypeId]) REFERENCES [dbo].[INV_TM_Type](Id),	
CONSTRAINT INV_TM_Details_CountryId  FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Ref_country](Id),	
CONSTRAINT INV_TM_Details_CityId FOREIGN KEY ([CityId]) REFERENCES [dbo].[Ref_City](Id),	
CONSTRAINT INV_TM_Details_ProvinceId  FOREIGN KEY ([ProvinceId]) REFERENCES [dbo].[Ref_Province](Id),	
CONSTRAINT INV_TM_Details_TravelCurrencyId  FOREIGN KEY ([TravelCurrencyId]) REFERENCES [dbo].[Ref_currency](Id),	
CONSTRAINT INV_TM_Details_SourceCurrencyId FOREIGN KEY ([SourceCurrencyId]) REFERENCES [dbo].[Ref_currency](Id),	
CONSTRAINT INV_TM_Details_InspPortCountyId  FOREIGN KEY ([InspPortCountyId]) REFERENCES [dbo].[Ref_county](Id),	
CONSTRAINT INV_TM_Details_CountyId FOREIGN KEY ([CountyId]) REFERENCES [dbo].[Ref_county](Id),	
CONSTRAINT INV_TM_Details_CreatedBy FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[IT_UserMaster](Id),	
CONSTRAINT INV_TM_Details_DeletedBy FOREIGN KEY ([DeletedBy]) REFERENCES [dbo].[IT_UserMaster](Id),
CONSTRAINT INV_TM_Details_UpdatedBy FOREIGN KEY ([UpdatedBy]) REFERENCES [dbo].[IT_UserMaster](Id),
CONSTRAINT FK_TRAVEL_MATRIX_PORT_CITY_ID FOREIGN KEY ([InspPortCityId]) REFERENCES [dbo].[REF_CITY]
)