CREATE TABLE [dbo].[IT_UserMaster]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Login_name] [nvarchar](50) NOT NULL,
	[FullName] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[Active] [bit] NOT NULL,
	[StatusId] [smallint] NOT NULL,
	[EntityId] INT NULL, 
	[StaffId] INT  NULL,
	[UserTypeId] INT NOT NULL,
	[CustomerId] INT NULL,
	[SupplierId] INT NULL,
	[FactoryId] INT NULL,
	[ChangePassword] BIT NULL, 
    [Fb_User_Id] INT NULL, 
    [CustomerContactId] INT NULL, 
    [SupplierContactId] INT NULL, 
    [FactoryContactId] INT NULL, 
    [CreatedBy] INT NULL, 
    [CreatedOn] DATETIME NULL, 
    [DeletedBy] INT NULL, 
    [DeletedOn] DATETIME NULL, 
	[UpdatedBy] INT NULL,
	[UpdatedOn] DATETIME NULL,
	[AuditAccess] BIT NULL,
	[InspectionAccess] BIT NULL,
	[TCFAccess] BIT NULL,
	[LabAccess] BIT NULL,
    [TCFUserID] INT NULL, 
	[FileUrl] NVARCHAR(max) NULL,
	[FileName] NVARCHAR(255) NULL,
    FOREIGN KEY([EntityId]) REFERENCES [AP_Entity](Id),
	FOREIGN KEY([StaffId]) REFERENCES [HR_Staff](Id),
	FOREIGN KEY([CustomerId]) REFERENCES [CU_Customer](Id),
	FOREIGN KEY([SupplierId]) REFERENCES [SU_Supplier](Id),
	FOREIGN KEY([FactoryId]) REFERENCES [SU_Supplier](Id),
	FOREIGN KEY([UserTypeId]) REFERENCES [IT_UserType](Id),
	FOREIGN KEY([CustomerContactId]) REFERENCES [Cu_Contact](Id),
	FOREIGN KEY([SupplierContactId]) REFERENCES [SU_Contact](Id),
	FOREIGN KEY([FactoryContactId]) REFERENCES [SU_Contact](Id),
	FOREIGN KEY([CreatedBy]) REFERENCES [IT_UserMaster](Id),
	FOREIGN KEY([DeletedBy]) REFERENCES [IT_UserMaster](Id),
	FOREIGN KEY([UpdatedBy]) REFERENCES [IT_UserMaster](Id)
)
