CREATE TABLE [dbo].[OM_Details]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [CustomerId] INT NULL, 
    [OfficeCountryId] INT NULL, 
    [QcId] INT NULL, 
    [OperationalCountryId] INT NULL, 
    [PurposeId] INT NULL, 
    [ServiceDate] DATETIME NULL, 
    [ManDay] FLOAT NULL, 
    [Remarks] NVARCHAR(1000) NULL, 
    [Active] BIT,
    [CreatedBy] INT NULL, 
    [CreatedOn] DATETIME NULL, 
    [UpdatedBy] INT NULL, 
    [UpdatedOn] DATETIME NULL, 
    [DeletedBy] INT NULL, 
    [DeletedOn] DATETIME NULL,
    [EntityId] INT NULL, 
    FOREIGN KEY (CustomerId) REFERENCES CU_Customer(Id),
    FOREIGN KEY (OfficeCountryId) REFERENCES REF_Country(Id),
    FOREIGN KEY (QcId) REFERENCES HR_Staff(Id),
    FOREIGN KEY (OperationalCountryId) REFERENCES REF_Country(Id),
    FOREIGN KEY (PurposeId) REFERENCES [OM_REF_Purpose](Id),
    FOREIGN KEY([CreatedBy]) REFERENCES [IT_UserMaster](Id),
    FOREIGN KEY([UpdatedBy]) REFERENCES [IT_UserMaster](Id),
    FOREIGN KEY([DeletedBy]) REFERENCES [IT_UserMaster](Id),
    FOREIGN KEY([EntityId]) REFERENCES [AP_Entity](Id)
)
