CREATE TABLE [dbo].[QU_Quotation_Insp]
(
	IdQuotation INT NOT NULL, 
	IdBooking INT NOT NULL,
	PRIMARY KEY (IdQuotation, IdBooking),
	[UnitPrice] FLOAT NULL, 
    [NoOfManDay] FLOAT NULL, 
    [InspFees] FLOAT NULL, 
    [TravelLand] FLOAT NULL, 
    [TravelAir] FLOAT NULL, 
    [TravelHotel] FLOAT NULL, 
    [TotalCost] FLOAT NULL,
	[InvoiceNo] NVARCHAR(1000) NULL, 
    [InvoiceDate] DATETIME NULL, 
    [InvoiceRemarks] NVARCHAR(2000) NULL, 
    [UpdatedBy] INT NULL, 
    [UpdatedOn] DATETIME NULL, 
    [NoOfTravelManDay] FLOAT NULL, 
    [TravelDistance] FLOAT NULL, 
    [TravelTime] FLOAT NULL, 
    [CalculatedWorkingHrs] FLOAT NULL, 
    [CalculatedWorkingManDay] FLOAT NULL, 
    Quantity Int NULL,
    BilledQtyType Int NULL,
    SuggestedManday Float NULL,
    FOREIGN KEY (BilledQtyType) REFERENCES INSP_REF_QuantityType(Id),
    FOREIGN KEY(IdQuotation) REFERENCES [dbo].[QU_Quotation](Id),
	FOREIGN KEY(IdBooking) REFERENCES [dbo].[INSP_Transaction](Id),
	FOREIGN KEY([UpdatedBy]) REFERENCES [dbo].[It_UserMaster](Id)
)
