CREATE TABLE QU_QUOTATION (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	CountryId INT NOT NULL, 
	ServiceId INT NOT NULL, 
	BillingMethodId INT NOT NULL,
	BillingPaidById INT NOT NULL,
	CustomerId INT NOT NULL,
	CustomerLegalName NVARCHAR(200) NOT NULL,
	SupplierId INT NOT NULL, 
	SupplierLegalName NVARCHAR(200) NOT NULL,
	FactoryId INT NOT NULL,
	LegalFactoryName NVARCHAR(200) NOT NULL,
	FactoryAddress NVARCHAR(600) NOT NULL,
	OfficeId  INT NOT NULL,  
	InspectionFees FLOAT NOT NULL,
	EstimatedManday FLOAT NOT NULL,
	CurrencyId INT NOT NULL, 
	TravelCostsAir FLOAT NULL,
	TravelCostsLand FLOAT NULL,
	TravelCostsHotel FLOAT NULL,
	OtherCosts FLOAT NULL,
	Discount FLOAT NULL,
	TotalCost FLOAT NOT NULL,
	ApiRemark NVARCHAR(600) NULL,
	CustomerRemark NVARCHAR(600) NULL,
	IdStatus INT NOT NULL DEFAULT(1), 
	CreatedDate DATETIME NOT NULL, 
	ApiInternalRemark NVARCHAR(3000) NULL,
	BillingEntity INT NULL, 
	[PaymentTerms] INT NULL, 
	[RuleId] INT Null,
	[PaymentTermsValue] NVARCHAR(200) NULL,
	[PaymentTermsCount] INT NULL,
	CONSTRAINT FK_Qu_Quotation_RuleId FOREIGN KEY (RuleId) REFERENCES [dbo].[CU_PR_Details](Id),
    FOREIGN KEY (CountryId) REFERENCES [dbo].[REF_COUNTRY](Id),
    FOREIGN KEY (ServiceId) REFERENCES [dbo].[REF_SERVICE](Id),
	FOREIGN KEY (BillingMethodId) REFERENCES [dbo].[QU_BillMethod](Id),
	FOREIGN KEY (BillingPaidById) REFERENCES [dbo].[QU_PaidBy](Id),
	FOREIGN KEY (CustomerId) REFERENCES [dbo].[CU_Customer](Id),
	FOREIGN KEY (SupplierId) REFERENCES [dbo].[SU_Supplier](Id),
	FOREIGN KEY (FactoryId) REFERENCES [dbo].[SU_Supplier](Id),
	FOREIGN KEY (OfficeId) REFERENCES [dbo].[REF_LOCATION](Id),
	FOREIGN KEY (CurrencyId) REFERENCES [dbo].[REF_CURRENCY](Id),
	FOREIGN KEY (IdStatus) REFERENCES QU_Status(Id),
	FOREIGN KEY (BillingEntity) REFERENCES [REF_Billing_Entity](Id),
	FOREIGN KEY (PaymentTerms) REFERENCES [REF_InvoiceType](Id)
 )