CREATE TABLE [dbo].[REF_Location](
	[Id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL PRIMARY KEY,
	[Address] [nvarchar](150) NOT NULL,
	[City_Id] [int] NOT NULL,
	[ZipCode] [nvarchar](30) NULL,
	[LocationType_Id] [int] NOT NULL,
	[Location_Name] [nvarchar](100) NOT NULL,
	[Master_Currency_Id] [int] NULL,
	[Default_Currency_Id] [int] NULL,
	[Tel] [nvarchar](100) NULL,
	[Fax] [nvarchar](40) NULL,
	[Email] [nvarchar](150) NULL,
	[ParentId] [int]  NULL,
	[Comment] [nvarchar](100) NULL,
	[Active] [bit] NOT NULL,
	[EntityId] INT NULL, 
	[OfficeCode] [nvarchar](200) NULL,
	[Address2] [nvarchar](500) NOT NULL,
	[HeadOffice] INT NULL,
	FOREIGN KEY([EntityId]) REFERENCES [AP_Entity](Id),
	FOREIGN KEY ([City_Id]) REFERENCES [dbo].[REF_City](Id),
	FOREIGN KEY ([LocationType_Id]) REFERENCES [dbo].[REF_LocationType](Id),
	FOREIGN KEY ([Master_Currency_Id]) REFERENCES [dbo].[REF_Currency](Id),
	FOREIGN KEY ([Default_Currency_Id]) REFERENCES [dbo].[REF_Currency](Id),
	FOREIGN KEY ([HeadOffice]) REFERENCES [dbo].[REF_Location](Id)
)