CREATE TABLE [dbo].[REP_REF_ToolType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ToolName] [nvarchar](50) NULL,
	[Active] [bit] NULL,
	[Sort] [int] NULL,
 CONSTRAINT [PK_REP_REF_ToolType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[REP_REF_ToolType] ADD  CONSTRAINT [DF_REP_REF_ToolType_Active]  DEFAULT ((1)) FOR [Active]
GO