
CREATE TABLE [dbo].[SU_Supplier](
	[Id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL PRIMARY KEY,
	[Supplier_Name] [nvarchar](100) NOT NULL,
	[Level_Id] [int] NULL,
	[Comments] [nvarchar](500) NULL,
	[Active] [bit] NOT NULL,
	[Type_id] [int] NULL,
	[LegalName] [nvarchar](50) NULL,
	[Email] [nvarchar](500) NULL,
	[Phone] [nvarchar](500) NULL,
	[Fax] [nvarchar](500) NULL,
	[Website] [nvarchar](500) NULL,
	[Mobile] [nvarchar](500) NULL,
	[LocalName] [nvarchar](500) NULL,
	[ContactPerson] [nvarchar](500) NULL,
	[CreatedDate] [datetime] NULL,
	[CreatedBy] [int] NULL,
	[GlCode] [varchar](100) NULL,
	[OwnerShip_Id] INT NULL,
	[total_staff] [nvarchar](50) NULL,
	[daily_production] [nvarchar](50) NULL,
	[Entity_Id] INT NOT NULL,
	[CreditTermId] INT NULL, 
    [StatusId] INT NULL, 
    [ModifiedBy] INT NULL, 
    [ModifiedOn] DATETIME NULL, 
    [DeletedBy] INT NULL, 
    [DeletedOn] DATETIME NULL, 
    [VATNo] NVARCHAR(500) NULL, 
    [Fb_FactSup_Id] INT NULL, 
	[CompanyId] [int] NULL,
    FOREIGN KEY([CompanyId]) REFERENCES [dbo].[AP_Entity](Id),
    FOREIGN KEY([Level_Id]) REFERENCES [SU_Level]([Id]),
	FOREIGN KEY([Type_id]) REFERENCES [SU_Type]([Id]),
	FOREIGN KEY([OwnerShip_Id]) REFERENCES [SU_OwnlerShip]([Id]),
	FOREIGN KEY([Entity_Id]) REFERENCES [AP_Entity]([Id]),
	FOREIGN KEY([CreditTermId]) REFERENCES [SU_CreditTerm]([Id]),
	FOREIGN KEY([StatusId]) REFERENCES [SU_Status]([Id]),
	FOREIGN KEY([ModifiedBy]) REFERENCES [It_UserMaster]([Id]),
	FOREIGN KEY([DeletedBy]) REFERENCES [It_UserMaster]([Id]),
	[IsEAQF] BIT NULL
	)


